// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: torchbringer/servers/grpc/torchbringer.proto

package torchbringer.servers.grpc;

public final class Torchbringer {
  private Torchbringer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:torchbringer.servers.grpc.Config)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string serializedConfig = 1;</code>
     * @return The serializedConfig.
     */
    java.lang.String getSerializedConfig();
    /**
     * <code>string serializedConfig = 1;</code>
     * @return The bytes for serializedConfig.
     */
    com.google.protobuf.ByteString
        getSerializedConfigBytes();
  }
  /**
   * Protobuf type {@code torchbringer.servers.grpc.Config}
   */
  public static final class Config extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:torchbringer.servers.grpc.Config)
      ConfigOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Config.newBuilder() to construct.
    private Config(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Config() {
      serializedConfig_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Config();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Config(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              serializedConfig_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return torchbringer.servers.grpc.Torchbringer.internal_static_torchbringer_servers_grpc_Config_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return torchbringer.servers.grpc.Torchbringer.internal_static_torchbringer_servers_grpc_Config_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              torchbringer.servers.grpc.Torchbringer.Config.class, torchbringer.servers.grpc.Torchbringer.Config.Builder.class);
    }

    public static final int SERIALIZEDCONFIG_FIELD_NUMBER = 1;
    private volatile java.lang.Object serializedConfig_;
    /**
     * <code>string serializedConfig = 1;</code>
     * @return The serializedConfig.
     */
    @java.lang.Override
    public java.lang.String getSerializedConfig() {
      java.lang.Object ref = serializedConfig_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serializedConfig_ = s;
        return s;
      }
    }
    /**
     * <code>string serializedConfig = 1;</code>
     * @return The bytes for serializedConfig.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSerializedConfigBytes() {
      java.lang.Object ref = serializedConfig_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serializedConfig_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSerializedConfigBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, serializedConfig_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSerializedConfigBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, serializedConfig_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof torchbringer.servers.grpc.Torchbringer.Config)) {
        return super.equals(obj);
      }
      torchbringer.servers.grpc.Torchbringer.Config other = (torchbringer.servers.grpc.Torchbringer.Config) obj;

      if (!getSerializedConfig()
          .equals(other.getSerializedConfig())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SERIALIZEDCONFIG_FIELD_NUMBER;
      hash = (53 * hash) + getSerializedConfig().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static torchbringer.servers.grpc.Torchbringer.Config parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static torchbringer.servers.grpc.Torchbringer.Config parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static torchbringer.servers.grpc.Torchbringer.Config parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static torchbringer.servers.grpc.Torchbringer.Config parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static torchbringer.servers.grpc.Torchbringer.Config parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static torchbringer.servers.grpc.Torchbringer.Config parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static torchbringer.servers.grpc.Torchbringer.Config parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static torchbringer.servers.grpc.Torchbringer.Config parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static torchbringer.servers.grpc.Torchbringer.Config parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static torchbringer.servers.grpc.Torchbringer.Config parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static torchbringer.servers.grpc.Torchbringer.Config parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static torchbringer.servers.grpc.Torchbringer.Config parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(torchbringer.servers.grpc.Torchbringer.Config prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code torchbringer.servers.grpc.Config}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:torchbringer.servers.grpc.Config)
        torchbringer.servers.grpc.Torchbringer.ConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return torchbringer.servers.grpc.Torchbringer.internal_static_torchbringer_servers_grpc_Config_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return torchbringer.servers.grpc.Torchbringer.internal_static_torchbringer_servers_grpc_Config_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                torchbringer.servers.grpc.Torchbringer.Config.class, torchbringer.servers.grpc.Torchbringer.Config.Builder.class);
      }

      // Construct using torchbringer.servers.grpc.Torchbringer.Config.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        serializedConfig_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return torchbringer.servers.grpc.Torchbringer.internal_static_torchbringer_servers_grpc_Config_descriptor;
      }

      @java.lang.Override
      public torchbringer.servers.grpc.Torchbringer.Config getDefaultInstanceForType() {
        return torchbringer.servers.grpc.Torchbringer.Config.getDefaultInstance();
      }

      @java.lang.Override
      public torchbringer.servers.grpc.Torchbringer.Config build() {
        torchbringer.servers.grpc.Torchbringer.Config result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public torchbringer.servers.grpc.Torchbringer.Config buildPartial() {
        torchbringer.servers.grpc.Torchbringer.Config result = new torchbringer.servers.grpc.Torchbringer.Config(this);
        result.serializedConfig_ = serializedConfig_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof torchbringer.servers.grpc.Torchbringer.Config) {
          return mergeFrom((torchbringer.servers.grpc.Torchbringer.Config)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(torchbringer.servers.grpc.Torchbringer.Config other) {
        if (other == torchbringer.servers.grpc.Torchbringer.Config.getDefaultInstance()) return this;
        if (!other.getSerializedConfig().isEmpty()) {
          serializedConfig_ = other.serializedConfig_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        torchbringer.servers.grpc.Torchbringer.Config parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (torchbringer.servers.grpc.Torchbringer.Config) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object serializedConfig_ = "";
      /**
       * <code>string serializedConfig = 1;</code>
       * @return The serializedConfig.
       */
      public java.lang.String getSerializedConfig() {
        java.lang.Object ref = serializedConfig_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          serializedConfig_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string serializedConfig = 1;</code>
       * @return The bytes for serializedConfig.
       */
      public com.google.protobuf.ByteString
          getSerializedConfigBytes() {
        java.lang.Object ref = serializedConfig_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serializedConfig_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string serializedConfig = 1;</code>
       * @param value The serializedConfig to set.
       * @return This builder for chaining.
       */
      public Builder setSerializedConfig(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        serializedConfig_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string serializedConfig = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSerializedConfig() {
        
        serializedConfig_ = getDefaultInstance().getSerializedConfig();
        onChanged();
        return this;
      }
      /**
       * <code>string serializedConfig = 1;</code>
       * @param value The bytes for serializedConfig to set.
       * @return This builder for chaining.
       */
      public Builder setSerializedConfigBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        serializedConfig_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:torchbringer.servers.grpc.Config)
    }

    // @@protoc_insertion_point(class_scope:torchbringer.servers.grpc.Config)
    private static final torchbringer.servers.grpc.Torchbringer.Config DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new torchbringer.servers.grpc.Torchbringer.Config();
    }

    public static torchbringer.servers.grpc.Torchbringer.Config getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Config>
        PARSER = new com.google.protobuf.AbstractParser<Config>() {
      @java.lang.Override
      public Config parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Config(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Config> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Config> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public torchbringer.servers.grpc.Torchbringer.Config getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ConfirmationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:torchbringer.servers.grpc.Confirmation)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string info = 1;</code>
     * @return The info.
     */
    java.lang.String getInfo();
    /**
     * <code>string info = 1;</code>
     * @return The bytes for info.
     */
    com.google.protobuf.ByteString
        getInfoBytes();
  }
  /**
   * Protobuf type {@code torchbringer.servers.grpc.Confirmation}
   */
  public static final class Confirmation extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:torchbringer.servers.grpc.Confirmation)
      ConfirmationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Confirmation.newBuilder() to construct.
    private Confirmation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Confirmation() {
      info_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Confirmation();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Confirmation(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              info_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return torchbringer.servers.grpc.Torchbringer.internal_static_torchbringer_servers_grpc_Confirmation_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return torchbringer.servers.grpc.Torchbringer.internal_static_torchbringer_servers_grpc_Confirmation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              torchbringer.servers.grpc.Torchbringer.Confirmation.class, torchbringer.servers.grpc.Torchbringer.Confirmation.Builder.class);
    }

    public static final int INFO_FIELD_NUMBER = 1;
    private volatile java.lang.Object info_;
    /**
     * <code>string info = 1;</code>
     * @return The info.
     */
    @java.lang.Override
    public java.lang.String getInfo() {
      java.lang.Object ref = info_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        info_ = s;
        return s;
      }
    }
    /**
     * <code>string info = 1;</code>
     * @return The bytes for info.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getInfoBytes() {
      java.lang.Object ref = info_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        info_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getInfoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, info_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getInfoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, info_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof torchbringer.servers.grpc.Torchbringer.Confirmation)) {
        return super.equals(obj);
      }
      torchbringer.servers.grpc.Torchbringer.Confirmation other = (torchbringer.servers.grpc.Torchbringer.Confirmation) obj;

      if (!getInfo()
          .equals(other.getInfo())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + INFO_FIELD_NUMBER;
      hash = (53 * hash) + getInfo().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static torchbringer.servers.grpc.Torchbringer.Confirmation parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static torchbringer.servers.grpc.Torchbringer.Confirmation parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static torchbringer.servers.grpc.Torchbringer.Confirmation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static torchbringer.servers.grpc.Torchbringer.Confirmation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static torchbringer.servers.grpc.Torchbringer.Confirmation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static torchbringer.servers.grpc.Torchbringer.Confirmation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static torchbringer.servers.grpc.Torchbringer.Confirmation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static torchbringer.servers.grpc.Torchbringer.Confirmation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static torchbringer.servers.grpc.Torchbringer.Confirmation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static torchbringer.servers.grpc.Torchbringer.Confirmation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static torchbringer.servers.grpc.Torchbringer.Confirmation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static torchbringer.servers.grpc.Torchbringer.Confirmation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(torchbringer.servers.grpc.Torchbringer.Confirmation prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code torchbringer.servers.grpc.Confirmation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:torchbringer.servers.grpc.Confirmation)
        torchbringer.servers.grpc.Torchbringer.ConfirmationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return torchbringer.servers.grpc.Torchbringer.internal_static_torchbringer_servers_grpc_Confirmation_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return torchbringer.servers.grpc.Torchbringer.internal_static_torchbringer_servers_grpc_Confirmation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                torchbringer.servers.grpc.Torchbringer.Confirmation.class, torchbringer.servers.grpc.Torchbringer.Confirmation.Builder.class);
      }

      // Construct using torchbringer.servers.grpc.Torchbringer.Confirmation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        info_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return torchbringer.servers.grpc.Torchbringer.internal_static_torchbringer_servers_grpc_Confirmation_descriptor;
      }

      @java.lang.Override
      public torchbringer.servers.grpc.Torchbringer.Confirmation getDefaultInstanceForType() {
        return torchbringer.servers.grpc.Torchbringer.Confirmation.getDefaultInstance();
      }

      @java.lang.Override
      public torchbringer.servers.grpc.Torchbringer.Confirmation build() {
        torchbringer.servers.grpc.Torchbringer.Confirmation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public torchbringer.servers.grpc.Torchbringer.Confirmation buildPartial() {
        torchbringer.servers.grpc.Torchbringer.Confirmation result = new torchbringer.servers.grpc.Torchbringer.Confirmation(this);
        result.info_ = info_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof torchbringer.servers.grpc.Torchbringer.Confirmation) {
          return mergeFrom((torchbringer.servers.grpc.Torchbringer.Confirmation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(torchbringer.servers.grpc.Torchbringer.Confirmation other) {
        if (other == torchbringer.servers.grpc.Torchbringer.Confirmation.getDefaultInstance()) return this;
        if (!other.getInfo().isEmpty()) {
          info_ = other.info_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        torchbringer.servers.grpc.Torchbringer.Confirmation parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (torchbringer.servers.grpc.Torchbringer.Confirmation) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object info_ = "";
      /**
       * <code>string info = 1;</code>
       * @return The info.
       */
      public java.lang.String getInfo() {
        java.lang.Object ref = info_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          info_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string info = 1;</code>
       * @return The bytes for info.
       */
      public com.google.protobuf.ByteString
          getInfoBytes() {
        java.lang.Object ref = info_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          info_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string info = 1;</code>
       * @param value The info to set.
       * @return This builder for chaining.
       */
      public Builder setInfo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        info_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string info = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearInfo() {
        
        info_ = getDefaultInstance().getInfo();
        onChanged();
        return this;
      }
      /**
       * <code>string info = 1;</code>
       * @param value The bytes for info to set.
       * @return This builder for chaining.
       */
      public Builder setInfoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        info_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:torchbringer.servers.grpc.Confirmation)
    }

    // @@protoc_insertion_point(class_scope:torchbringer.servers.grpc.Confirmation)
    private static final torchbringer.servers.grpc.Torchbringer.Confirmation DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new torchbringer.servers.grpc.Torchbringer.Confirmation();
    }

    public static torchbringer.servers.grpc.Torchbringer.Confirmation getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Confirmation>
        PARSER = new com.google.protobuf.AbstractParser<Confirmation>() {
      @java.lang.Override
      public Confirmation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Confirmation(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Confirmation> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Confirmation> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public torchbringer.servers.grpc.Torchbringer.Confirmation getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MatrixOrBuilder extends
      // @@protoc_insertion_point(interface_extends:torchbringer.servers.grpc.Matrix)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated int32 dimensions = 1;</code>
     * @return A list containing the dimensions.
     */
    java.util.List<java.lang.Integer> getDimensionsList();
    /**
     * <code>repeated int32 dimensions = 1;</code>
     * @return The count of dimensions.
     */
    int getDimensionsCount();
    /**
     * <code>repeated int32 dimensions = 1;</code>
     * @param index The index of the element to return.
     * @return The dimensions at the given index.
     */
    int getDimensions(int index);

    /**
     * <code>repeated float values = 2;</code>
     * @return A list containing the values.
     */
    java.util.List<java.lang.Float> getValuesList();
    /**
     * <code>repeated float values = 2;</code>
     * @return The count of values.
     */
    int getValuesCount();
    /**
     * <code>repeated float values = 2;</code>
     * @param index The index of the element to return.
     * @return The values at the given index.
     */
    float getValues(int index);
  }
  /**
   * Protobuf type {@code torchbringer.servers.grpc.Matrix}
   */
  public static final class Matrix extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:torchbringer.servers.grpc.Matrix)
      MatrixOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Matrix.newBuilder() to construct.
    private Matrix(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Matrix() {
      dimensions_ = emptyIntList();
      values_ = emptyFloatList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Matrix();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Matrix(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                dimensions_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              dimensions_.addInt(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                dimensions_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                dimensions_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 21: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                values_ = newFloatList();
                mutable_bitField0_ |= 0x00000002;
              }
              values_.addFloat(input.readFloat());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) != 0) && input.getBytesUntilLimit() > 0) {
                values_ = newFloatList();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                values_.addFloat(input.readFloat());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          dimensions_.makeImmutable(); // C
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          values_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return torchbringer.servers.grpc.Torchbringer.internal_static_torchbringer_servers_grpc_Matrix_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return torchbringer.servers.grpc.Torchbringer.internal_static_torchbringer_servers_grpc_Matrix_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              torchbringer.servers.grpc.Torchbringer.Matrix.class, torchbringer.servers.grpc.Torchbringer.Matrix.Builder.class);
    }

    public static final int DIMENSIONS_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.IntList dimensions_;
    /**
     * <code>repeated int32 dimensions = 1;</code>
     * @return A list containing the dimensions.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getDimensionsList() {
      return dimensions_;
    }
    /**
     * <code>repeated int32 dimensions = 1;</code>
     * @return The count of dimensions.
     */
    public int getDimensionsCount() {
      return dimensions_.size();
    }
    /**
     * <code>repeated int32 dimensions = 1;</code>
     * @param index The index of the element to return.
     * @return The dimensions at the given index.
     */
    public int getDimensions(int index) {
      return dimensions_.getInt(index);
    }
    private int dimensionsMemoizedSerializedSize = -1;

    public static final int VALUES_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.FloatList values_;
    /**
     * <code>repeated float values = 2;</code>
     * @return A list containing the values.
     */
    @java.lang.Override
    public java.util.List<java.lang.Float>
        getValuesList() {
      return values_;
    }
    /**
     * <code>repeated float values = 2;</code>
     * @return The count of values.
     */
    public int getValuesCount() {
      return values_.size();
    }
    /**
     * <code>repeated float values = 2;</code>
     * @param index The index of the element to return.
     * @return The values at the given index.
     */
    public float getValues(int index) {
      return values_.getFloat(index);
    }
    private int valuesMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getDimensionsList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(dimensionsMemoizedSerializedSize);
      }
      for (int i = 0; i < dimensions_.size(); i++) {
        output.writeInt32NoTag(dimensions_.getInt(i));
      }
      if (getValuesList().size() > 0) {
        output.writeUInt32NoTag(18);
        output.writeUInt32NoTag(valuesMemoizedSerializedSize);
      }
      for (int i = 0; i < values_.size(); i++) {
        output.writeFloatNoTag(values_.getFloat(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < dimensions_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dimensions_.getInt(i));
        }
        size += dataSize;
        if (!getDimensionsList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        dimensionsMemoizedSerializedSize = dataSize;
      }
      {
        int dataSize = 0;
        dataSize = 4 * getValuesList().size();
        size += dataSize;
        if (!getValuesList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        valuesMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof torchbringer.servers.grpc.Torchbringer.Matrix)) {
        return super.equals(obj);
      }
      torchbringer.servers.grpc.Torchbringer.Matrix other = (torchbringer.servers.grpc.Torchbringer.Matrix) obj;

      if (!getDimensionsList()
          .equals(other.getDimensionsList())) return false;
      if (!getValuesList()
          .equals(other.getValuesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getDimensionsCount() > 0) {
        hash = (37 * hash) + DIMENSIONS_FIELD_NUMBER;
        hash = (53 * hash) + getDimensionsList().hashCode();
      }
      if (getValuesCount() > 0) {
        hash = (37 * hash) + VALUES_FIELD_NUMBER;
        hash = (53 * hash) + getValuesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static torchbringer.servers.grpc.Torchbringer.Matrix parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static torchbringer.servers.grpc.Torchbringer.Matrix parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static torchbringer.servers.grpc.Torchbringer.Matrix parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static torchbringer.servers.grpc.Torchbringer.Matrix parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static torchbringer.servers.grpc.Torchbringer.Matrix parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static torchbringer.servers.grpc.Torchbringer.Matrix parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static torchbringer.servers.grpc.Torchbringer.Matrix parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static torchbringer.servers.grpc.Torchbringer.Matrix parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static torchbringer.servers.grpc.Torchbringer.Matrix parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static torchbringer.servers.grpc.Torchbringer.Matrix parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static torchbringer.servers.grpc.Torchbringer.Matrix parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static torchbringer.servers.grpc.Torchbringer.Matrix parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(torchbringer.servers.grpc.Torchbringer.Matrix prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code torchbringer.servers.grpc.Matrix}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:torchbringer.servers.grpc.Matrix)
        torchbringer.servers.grpc.Torchbringer.MatrixOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return torchbringer.servers.grpc.Torchbringer.internal_static_torchbringer_servers_grpc_Matrix_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return torchbringer.servers.grpc.Torchbringer.internal_static_torchbringer_servers_grpc_Matrix_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                torchbringer.servers.grpc.Torchbringer.Matrix.class, torchbringer.servers.grpc.Torchbringer.Matrix.Builder.class);
      }

      // Construct using torchbringer.servers.grpc.Torchbringer.Matrix.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        dimensions_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        values_ = emptyFloatList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return torchbringer.servers.grpc.Torchbringer.internal_static_torchbringer_servers_grpc_Matrix_descriptor;
      }

      @java.lang.Override
      public torchbringer.servers.grpc.Torchbringer.Matrix getDefaultInstanceForType() {
        return torchbringer.servers.grpc.Torchbringer.Matrix.getDefaultInstance();
      }

      @java.lang.Override
      public torchbringer.servers.grpc.Torchbringer.Matrix build() {
        torchbringer.servers.grpc.Torchbringer.Matrix result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public torchbringer.servers.grpc.Torchbringer.Matrix buildPartial() {
        torchbringer.servers.grpc.Torchbringer.Matrix result = new torchbringer.servers.grpc.Torchbringer.Matrix(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          dimensions_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.dimensions_ = dimensions_;
        if (((bitField0_ & 0x00000002) != 0)) {
          values_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.values_ = values_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof torchbringer.servers.grpc.Torchbringer.Matrix) {
          return mergeFrom((torchbringer.servers.grpc.Torchbringer.Matrix)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(torchbringer.servers.grpc.Torchbringer.Matrix other) {
        if (other == torchbringer.servers.grpc.Torchbringer.Matrix.getDefaultInstance()) return this;
        if (!other.dimensions_.isEmpty()) {
          if (dimensions_.isEmpty()) {
            dimensions_ = other.dimensions_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDimensionsIsMutable();
            dimensions_.addAll(other.dimensions_);
          }
          onChanged();
        }
        if (!other.values_.isEmpty()) {
          if (values_.isEmpty()) {
            values_ = other.values_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureValuesIsMutable();
            values_.addAll(other.values_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        torchbringer.servers.grpc.Torchbringer.Matrix parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (torchbringer.servers.grpc.Torchbringer.Matrix) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Internal.IntList dimensions_ = emptyIntList();
      private void ensureDimensionsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          dimensions_ = mutableCopy(dimensions_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 dimensions = 1;</code>
       * @return A list containing the dimensions.
       */
      public java.util.List<java.lang.Integer>
          getDimensionsList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(dimensions_) : dimensions_;
      }
      /**
       * <code>repeated int32 dimensions = 1;</code>
       * @return The count of dimensions.
       */
      public int getDimensionsCount() {
        return dimensions_.size();
      }
      /**
       * <code>repeated int32 dimensions = 1;</code>
       * @param index The index of the element to return.
       * @return The dimensions at the given index.
       */
      public int getDimensions(int index) {
        return dimensions_.getInt(index);
      }
      /**
       * <code>repeated int32 dimensions = 1;</code>
       * @param index The index to set the value at.
       * @param value The dimensions to set.
       * @return This builder for chaining.
       */
      public Builder setDimensions(
          int index, int value) {
        ensureDimensionsIsMutable();
        dimensions_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 dimensions = 1;</code>
       * @param value The dimensions to add.
       * @return This builder for chaining.
       */
      public Builder addDimensions(int value) {
        ensureDimensionsIsMutable();
        dimensions_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 dimensions = 1;</code>
       * @param values The dimensions to add.
       * @return This builder for chaining.
       */
      public Builder addAllDimensions(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureDimensionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, dimensions_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 dimensions = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDimensions() {
        dimensions_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.FloatList values_ = emptyFloatList();
      private void ensureValuesIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          values_ = mutableCopy(values_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated float values = 2;</code>
       * @return A list containing the values.
       */
      public java.util.List<java.lang.Float>
          getValuesList() {
        return ((bitField0_ & 0x00000002) != 0) ?
                 java.util.Collections.unmodifiableList(values_) : values_;
      }
      /**
       * <code>repeated float values = 2;</code>
       * @return The count of values.
       */
      public int getValuesCount() {
        return values_.size();
      }
      /**
       * <code>repeated float values = 2;</code>
       * @param index The index of the element to return.
       * @return The values at the given index.
       */
      public float getValues(int index) {
        return values_.getFloat(index);
      }
      /**
       * <code>repeated float values = 2;</code>
       * @param index The index to set the value at.
       * @param value The values to set.
       * @return This builder for chaining.
       */
      public Builder setValues(
          int index, float value) {
        ensureValuesIsMutable();
        values_.setFloat(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float values = 2;</code>
       * @param value The values to add.
       * @return This builder for chaining.
       */
      public Builder addValues(float value) {
        ensureValuesIsMutable();
        values_.addFloat(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float values = 2;</code>
       * @param values The values to add.
       * @return This builder for chaining.
       */
      public Builder addAllValues(
          java.lang.Iterable<? extends java.lang.Float> values) {
        ensureValuesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, values_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float values = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearValues() {
        values_ = emptyFloatList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:torchbringer.servers.grpc.Matrix)
    }

    // @@protoc_insertion_point(class_scope:torchbringer.servers.grpc.Matrix)
    private static final torchbringer.servers.grpc.Torchbringer.Matrix DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new torchbringer.servers.grpc.Torchbringer.Matrix();
    }

    public static torchbringer.servers.grpc.Torchbringer.Matrix getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Matrix>
        PARSER = new com.google.protobuf.AbstractParser<Matrix>() {
      @java.lang.Override
      public Matrix parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Matrix(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Matrix> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Matrix> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public torchbringer.servers.grpc.Torchbringer.Matrix getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PerceptOrBuilder extends
      // @@protoc_insertion_point(interface_extends:torchbringer.servers.grpc.Percept)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.torchbringer.servers.grpc.Matrix state = 1;</code>
     * @return Whether the state field is set.
     */
    boolean hasState();
    /**
     * <code>.torchbringer.servers.grpc.Matrix state = 1;</code>
     * @return The state.
     */
    torchbringer.servers.grpc.Torchbringer.Matrix getState();
    /**
     * <code>.torchbringer.servers.grpc.Matrix state = 1;</code>
     */
    torchbringer.servers.grpc.Torchbringer.MatrixOrBuilder getStateOrBuilder();

    /**
     * <code>float reward = 2;</code>
     * @return The reward.
     */
    float getReward();

    /**
     * <code>bool terminal = 3;</code>
     * @return The terminal.
     */
    boolean getTerminal();
  }
  /**
   * Protobuf type {@code torchbringer.servers.grpc.Percept}
   */
  public static final class Percept extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:torchbringer.servers.grpc.Percept)
      PerceptOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Percept.newBuilder() to construct.
    private Percept(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Percept() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Percept();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Percept(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              torchbringer.servers.grpc.Torchbringer.Matrix.Builder subBuilder = null;
              if (state_ != null) {
                subBuilder = state_.toBuilder();
              }
              state_ = input.readMessage(torchbringer.servers.grpc.Torchbringer.Matrix.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(state_);
                state_ = subBuilder.buildPartial();
              }

              break;
            }
            case 21: {

              reward_ = input.readFloat();
              break;
            }
            case 24: {

              terminal_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return torchbringer.servers.grpc.Torchbringer.internal_static_torchbringer_servers_grpc_Percept_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return torchbringer.servers.grpc.Torchbringer.internal_static_torchbringer_servers_grpc_Percept_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              torchbringer.servers.grpc.Torchbringer.Percept.class, torchbringer.servers.grpc.Torchbringer.Percept.Builder.class);
    }

    public static final int STATE_FIELD_NUMBER = 1;
    private torchbringer.servers.grpc.Torchbringer.Matrix state_;
    /**
     * <code>.torchbringer.servers.grpc.Matrix state = 1;</code>
     * @return Whether the state field is set.
     */
    @java.lang.Override
    public boolean hasState() {
      return state_ != null;
    }
    /**
     * <code>.torchbringer.servers.grpc.Matrix state = 1;</code>
     * @return The state.
     */
    @java.lang.Override
    public torchbringer.servers.grpc.Torchbringer.Matrix getState() {
      return state_ == null ? torchbringer.servers.grpc.Torchbringer.Matrix.getDefaultInstance() : state_;
    }
    /**
     * <code>.torchbringer.servers.grpc.Matrix state = 1;</code>
     */
    @java.lang.Override
    public torchbringer.servers.grpc.Torchbringer.MatrixOrBuilder getStateOrBuilder() {
      return getState();
    }

    public static final int REWARD_FIELD_NUMBER = 2;
    private float reward_;
    /**
     * <code>float reward = 2;</code>
     * @return The reward.
     */
    @java.lang.Override
    public float getReward() {
      return reward_;
    }

    public static final int TERMINAL_FIELD_NUMBER = 3;
    private boolean terminal_;
    /**
     * <code>bool terminal = 3;</code>
     * @return The terminal.
     */
    @java.lang.Override
    public boolean getTerminal() {
      return terminal_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (state_ != null) {
        output.writeMessage(1, getState());
      }
      if (reward_ != 0F) {
        output.writeFloat(2, reward_);
      }
      if (terminal_ != false) {
        output.writeBool(3, terminal_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (state_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getState());
      }
      if (reward_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, reward_);
      }
      if (terminal_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, terminal_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof torchbringer.servers.grpc.Torchbringer.Percept)) {
        return super.equals(obj);
      }
      torchbringer.servers.grpc.Torchbringer.Percept other = (torchbringer.servers.grpc.Torchbringer.Percept) obj;

      if (hasState() != other.hasState()) return false;
      if (hasState()) {
        if (!getState()
            .equals(other.getState())) return false;
      }
      if (java.lang.Float.floatToIntBits(getReward())
          != java.lang.Float.floatToIntBits(
              other.getReward())) return false;
      if (getTerminal()
          != other.getTerminal()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasState()) {
        hash = (37 * hash) + STATE_FIELD_NUMBER;
        hash = (53 * hash) + getState().hashCode();
      }
      hash = (37 * hash) + REWARD_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getReward());
      hash = (37 * hash) + TERMINAL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getTerminal());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static torchbringer.servers.grpc.Torchbringer.Percept parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static torchbringer.servers.grpc.Torchbringer.Percept parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static torchbringer.servers.grpc.Torchbringer.Percept parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static torchbringer.servers.grpc.Torchbringer.Percept parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static torchbringer.servers.grpc.Torchbringer.Percept parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static torchbringer.servers.grpc.Torchbringer.Percept parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static torchbringer.servers.grpc.Torchbringer.Percept parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static torchbringer.servers.grpc.Torchbringer.Percept parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static torchbringer.servers.grpc.Torchbringer.Percept parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static torchbringer.servers.grpc.Torchbringer.Percept parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static torchbringer.servers.grpc.Torchbringer.Percept parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static torchbringer.servers.grpc.Torchbringer.Percept parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(torchbringer.servers.grpc.Torchbringer.Percept prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code torchbringer.servers.grpc.Percept}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:torchbringer.servers.grpc.Percept)
        torchbringer.servers.grpc.Torchbringer.PerceptOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return torchbringer.servers.grpc.Torchbringer.internal_static_torchbringer_servers_grpc_Percept_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return torchbringer.servers.grpc.Torchbringer.internal_static_torchbringer_servers_grpc_Percept_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                torchbringer.servers.grpc.Torchbringer.Percept.class, torchbringer.servers.grpc.Torchbringer.Percept.Builder.class);
      }

      // Construct using torchbringer.servers.grpc.Torchbringer.Percept.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (stateBuilder_ == null) {
          state_ = null;
        } else {
          state_ = null;
          stateBuilder_ = null;
        }
        reward_ = 0F;

        terminal_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return torchbringer.servers.grpc.Torchbringer.internal_static_torchbringer_servers_grpc_Percept_descriptor;
      }

      @java.lang.Override
      public torchbringer.servers.grpc.Torchbringer.Percept getDefaultInstanceForType() {
        return torchbringer.servers.grpc.Torchbringer.Percept.getDefaultInstance();
      }

      @java.lang.Override
      public torchbringer.servers.grpc.Torchbringer.Percept build() {
        torchbringer.servers.grpc.Torchbringer.Percept result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public torchbringer.servers.grpc.Torchbringer.Percept buildPartial() {
        torchbringer.servers.grpc.Torchbringer.Percept result = new torchbringer.servers.grpc.Torchbringer.Percept(this);
        if (stateBuilder_ == null) {
          result.state_ = state_;
        } else {
          result.state_ = stateBuilder_.build();
        }
        result.reward_ = reward_;
        result.terminal_ = terminal_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof torchbringer.servers.grpc.Torchbringer.Percept) {
          return mergeFrom((torchbringer.servers.grpc.Torchbringer.Percept)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(torchbringer.servers.grpc.Torchbringer.Percept other) {
        if (other == torchbringer.servers.grpc.Torchbringer.Percept.getDefaultInstance()) return this;
        if (other.hasState()) {
          mergeState(other.getState());
        }
        if (other.getReward() != 0F) {
          setReward(other.getReward());
        }
        if (other.getTerminal() != false) {
          setTerminal(other.getTerminal());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        torchbringer.servers.grpc.Torchbringer.Percept parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (torchbringer.servers.grpc.Torchbringer.Percept) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private torchbringer.servers.grpc.Torchbringer.Matrix state_;
      private com.google.protobuf.SingleFieldBuilderV3<
          torchbringer.servers.grpc.Torchbringer.Matrix, torchbringer.servers.grpc.Torchbringer.Matrix.Builder, torchbringer.servers.grpc.Torchbringer.MatrixOrBuilder> stateBuilder_;
      /**
       * <code>.torchbringer.servers.grpc.Matrix state = 1;</code>
       * @return Whether the state field is set.
       */
      public boolean hasState() {
        return stateBuilder_ != null || state_ != null;
      }
      /**
       * <code>.torchbringer.servers.grpc.Matrix state = 1;</code>
       * @return The state.
       */
      public torchbringer.servers.grpc.Torchbringer.Matrix getState() {
        if (stateBuilder_ == null) {
          return state_ == null ? torchbringer.servers.grpc.Torchbringer.Matrix.getDefaultInstance() : state_;
        } else {
          return stateBuilder_.getMessage();
        }
      }
      /**
       * <code>.torchbringer.servers.grpc.Matrix state = 1;</code>
       */
      public Builder setState(torchbringer.servers.grpc.Torchbringer.Matrix value) {
        if (stateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          state_ = value;
          onChanged();
        } else {
          stateBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.torchbringer.servers.grpc.Matrix state = 1;</code>
       */
      public Builder setState(
          torchbringer.servers.grpc.Torchbringer.Matrix.Builder builderForValue) {
        if (stateBuilder_ == null) {
          state_ = builderForValue.build();
          onChanged();
        } else {
          stateBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.torchbringer.servers.grpc.Matrix state = 1;</code>
       */
      public Builder mergeState(torchbringer.servers.grpc.Torchbringer.Matrix value) {
        if (stateBuilder_ == null) {
          if (state_ != null) {
            state_ =
              torchbringer.servers.grpc.Torchbringer.Matrix.newBuilder(state_).mergeFrom(value).buildPartial();
          } else {
            state_ = value;
          }
          onChanged();
        } else {
          stateBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.torchbringer.servers.grpc.Matrix state = 1;</code>
       */
      public Builder clearState() {
        if (stateBuilder_ == null) {
          state_ = null;
          onChanged();
        } else {
          state_ = null;
          stateBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.torchbringer.servers.grpc.Matrix state = 1;</code>
       */
      public torchbringer.servers.grpc.Torchbringer.Matrix.Builder getStateBuilder() {
        
        onChanged();
        return getStateFieldBuilder().getBuilder();
      }
      /**
       * <code>.torchbringer.servers.grpc.Matrix state = 1;</code>
       */
      public torchbringer.servers.grpc.Torchbringer.MatrixOrBuilder getStateOrBuilder() {
        if (stateBuilder_ != null) {
          return stateBuilder_.getMessageOrBuilder();
        } else {
          return state_ == null ?
              torchbringer.servers.grpc.Torchbringer.Matrix.getDefaultInstance() : state_;
        }
      }
      /**
       * <code>.torchbringer.servers.grpc.Matrix state = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          torchbringer.servers.grpc.Torchbringer.Matrix, torchbringer.servers.grpc.Torchbringer.Matrix.Builder, torchbringer.servers.grpc.Torchbringer.MatrixOrBuilder> 
          getStateFieldBuilder() {
        if (stateBuilder_ == null) {
          stateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              torchbringer.servers.grpc.Torchbringer.Matrix, torchbringer.servers.grpc.Torchbringer.Matrix.Builder, torchbringer.servers.grpc.Torchbringer.MatrixOrBuilder>(
                  getState(),
                  getParentForChildren(),
                  isClean());
          state_ = null;
        }
        return stateBuilder_;
      }

      private float reward_ ;
      /**
       * <code>float reward = 2;</code>
       * @return The reward.
       */
      @java.lang.Override
      public float getReward() {
        return reward_;
      }
      /**
       * <code>float reward = 2;</code>
       * @param value The reward to set.
       * @return This builder for chaining.
       */
      public Builder setReward(float value) {
        
        reward_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float reward = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearReward() {
        
        reward_ = 0F;
        onChanged();
        return this;
      }

      private boolean terminal_ ;
      /**
       * <code>bool terminal = 3;</code>
       * @return The terminal.
       */
      @java.lang.Override
      public boolean getTerminal() {
        return terminal_;
      }
      /**
       * <code>bool terminal = 3;</code>
       * @param value The terminal to set.
       * @return This builder for chaining.
       */
      public Builder setTerminal(boolean value) {
        
        terminal_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool terminal = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTerminal() {
        
        terminal_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:torchbringer.servers.grpc.Percept)
    }

    // @@protoc_insertion_point(class_scope:torchbringer.servers.grpc.Percept)
    private static final torchbringer.servers.grpc.Torchbringer.Percept DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new torchbringer.servers.grpc.Torchbringer.Percept();
    }

    public static torchbringer.servers.grpc.Torchbringer.Percept getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Percept>
        PARSER = new com.google.protobuf.AbstractParser<Percept>() {
      @java.lang.Override
      public Percept parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Percept(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Percept> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Percept> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public torchbringer.servers.grpc.Torchbringer.Percept getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_torchbringer_servers_grpc_Config_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_torchbringer_servers_grpc_Config_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_torchbringer_servers_grpc_Confirmation_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_torchbringer_servers_grpc_Confirmation_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_torchbringer_servers_grpc_Matrix_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_torchbringer_servers_grpc_Matrix_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_torchbringer_servers_grpc_Percept_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_torchbringer_servers_grpc_Percept_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,torchbringer/servers/grpc/torchbringer" +
      ".proto\022\031torchbringer.servers.grpc\"\"\n\006Con" +
      "fig\022\030\n\020serializedConfig\030\001 \001(\t\"\034\n\014Confirm" +
      "ation\022\014\n\004info\030\001 \001(\t\",\n\006Matrix\022\022\n\ndimensi" +
      "ons\030\001 \003(\005\022\016\n\006values\030\002 \003(\002\"]\n\007Percept\0220\n\005" +
      "state\030\001 \001(\0132!.torchbringer.servers.grpc." +
      "Matrix\022\016\n\006reward\030\002 \001(\002\022\020\n\010terminal\030\003 \001(\010" +
      "2\304\001\n\025TorchBringerGRPCAgent\022Z\n\ninitialize" +
      "\022!.torchbringer.servers.grpc.Config\032\'.to" +
      "rchbringer.servers.grpc.Confirmation\"\000\022O" +
      "\n\004step\022\".torchbringer.servers.grpc.Perce" +
      "pt\032!.torchbringer.servers.grpc.Matrix\"\000b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_torchbringer_servers_grpc_Config_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_torchbringer_servers_grpc_Config_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_torchbringer_servers_grpc_Config_descriptor,
        new java.lang.String[] { "SerializedConfig", });
    internal_static_torchbringer_servers_grpc_Confirmation_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_torchbringer_servers_grpc_Confirmation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_torchbringer_servers_grpc_Confirmation_descriptor,
        new java.lang.String[] { "Info", });
    internal_static_torchbringer_servers_grpc_Matrix_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_torchbringer_servers_grpc_Matrix_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_torchbringer_servers_grpc_Matrix_descriptor,
        new java.lang.String[] { "Dimensions", "Values", });
    internal_static_torchbringer_servers_grpc_Percept_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_torchbringer_servers_grpc_Percept_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_torchbringer_servers_grpc_Percept_descriptor,
        new java.lang.String[] { "State", "Reward", "Terminal", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
